//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManager_Csharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionId { get; set; }
        public int accountId { get; set; }
        public double amount { get; set; }
        public double balance { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
