//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManager_Csharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionId { get; set; }
        public int accountId { get; set; }
        public double amount { get; set; }
        public double balance { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
    

        
        public virtual Account Account { get; set; }

        public Transaction()
        {

        }

        /// <summary>
        /// Instantiates Transaction object. This is used to record successful transactions.
        /// </summary>
        /// <param name="transactionId"></param>
        /// <param name="accountId"></param>
        /// <param name="balance"></param>
        /// <param name="amount"></param>
        /// <param name="status"></param>
        /// <param name="date"></param>
        public Transaction(int accountId, double balance,
            int amount, String status, DateTime date)
        {
            this.accountId = accountId;
            this.balance = balance;
            this.amount = amount;
            this.status = status;
            this.date = date;

        }


        /// <summary>
        /// Returns human-readable datetime
        /// </summary>
        /// <returns></returns>
        public String getReadableDate()
        {
            return date.ToString("dd/MM/yyyy hh:mm:ss");
        }


        /// <summary>
        /// Pretty prints transaction information
        /// </summary>
        /// <returns></returns>
        public String prettyPrint()
        {
            return "Transaction id: " + transactionId + "\n"
                + "Account id: " + accountId + "\n"
                + "Balance: " + balance + "\n"
                + "Amount: " + amount + "\n"
                + "Status: " + status + "\n"
                + "Date: " + getReadableDate() + "\n";
        }
    }
}
